spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.register-mbeans=true
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true
server.forward-headers-strategy=framework
server.tomcat.threads.max=200
server.tomcat.accept-count=100
logging.level.com.bellatechnologies=INFO
logging.level.org.springframework.web.cors=INFO
management.endpoint.health.show-details=when_authorized
