// ============================================================================
// File: model/MpesaPayment.java
// ============================================================================
package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "MpesaPayments")
public class MpesaPayment {
    
    @DynamoDBHashKey(attributeName = "mpesaTransactionId")
    private String mpesaTransactionId; // M-Pesa receipt number
    
    @DynamoDBRangeKey(attributeName = "timestamp")
    private Long timestamp;
    
    @DynamoDBAttribute(attributeName = "paymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PaymentIdIndex")
    private String paymentId;
    
    @DynamoDBAttribute(attributeName = "checkoutRequestId")
    private String checkoutRequestId; // STK Push request ID
    
    @DynamoDBAttribute(attributeName = "merchantRequestId")
    private String merchantRequestId;
    
    @DynamoDBAttribute(attributeName = "phoneNumber")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String phoneNumber; // Encrypted
    
    @DynamoDBAttribute(attributeName = "amount")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String amount; // Encrypted
    
    @DynamoDBAttribute(attributeName = "accountReference")
    private String accountReference;
    
    @DynamoDBAttribute(attributeName = "transactionDesc")
    private String transactionDesc;
    
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "status")
    private PaymentStatus status;
    
    @DynamoDBAttribute(attributeName = "resultCode")
    private String resultCode;
    
    @DynamoDBAttribute(attributeName = "resultDesc")
    private String resultDesc;
    
    @DynamoDBAttribute(attributeName = "mpesaReceiptNumber")
    private String mpesaReceiptNumber;
    
    @DynamoDBAttribute(attributeName = "transactionDate")
    private String transactionDate;
    
    @DynamoDBAttribute(attributeName = "callbackPayload")
    private String callbackPayload; // Raw M-Pesa callback
    
    @DynamoDBAttribute(attributeName = "retryCount")
    private Integer retryCount;
    
    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;
    
    @DynamoDBAttribute(attributeName = "updatedAt")
    private String updatedAt;
    
    @DynamoDBVersionAttribute
    private Long version;
    
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.timestamp == null) {
            this.timestamp = Instant.now().toEpochMilli();
        }
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
        this.updatedAt = Instant.now().toString();
    }
}
