package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@DynamoDBTable(tableName = "mpesa_payments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MpesaPayment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    
    @DynamoDBAttribute
    private String phoneNumber;
    
    @DynamoDBAttribute
    private Double amount;
    
    @DynamoDBAttribute
    private String checkoutRequestId;
    
    @DynamoDBAttribute
    private String merchantRequestId;
    
    @DynamoDBAttribute
    private String transactionId;
    
    @DynamoDBAttribute
    private String mpesaTransactionId;
    
    @DynamoDBAttribute
    private String status; // String to store PaymentStatus enum name
    
    @DynamoDBAttribute
    private String paymentId;
    
    @DynamoDBAttribute
    private String accountReference;  // ADDED: Missing field
    
    @DynamoDBAttribute
    private String transactionDesc;  // ADDED: Missing field
    
    @DynamoDBAttribute
    private String resultCode;
    
    @DynamoDBAttribute
    private String resultDesc;
    
    @DynamoDBAttribute
    private String mpesaReceiptNumber;
    
    @DynamoDBAttribute
    private String transactionDate;
    
    @DynamoDBAttribute
    private String callbackPayload;
    
    @DynamoDBAttribute
    private String createdAt;
    
    @DynamoDBAttribute
    private String updatedAt;
    
    // Helper methods for PaymentStatus conversion
    public PaymentStatus getStatusEnum() {
        if (status == null) return PaymentStatus.PENDING;
        try {
            return PaymentStatus.valueOf(status);
        } catch (Exception e) {
            return PaymentStatus.PENDING;
        }
    }
    
    public void setStatus(PaymentStatus paymentStatus) {
        this.status = paymentStatus != null ? paymentStatus.name() : PaymentStatus.PENDING.name();
    }
    
    // Helper methods for Instant conversion
    public Instant getCreatedAtInstant() {
        if (createdAt == null) return null;
        try {
            return Instant.parse(createdAt);
        } catch (Exception e) {
            return null;
        }
    }
    
    public void setCreatedAt(Instant instant) {
        this.createdAt = instant != null ? instant.toString() : null;
    }
    
    public Instant getUpdatedAtInstant() {
        if (updatedAt == null) return null;
        try {
            return Instant.parse(updatedAt);
        } catch (Exception e) {
            return null;
        }
    }
    
    public void setUpdatedAt(Instant instant) {
        this.updatedAt = instant != null ? instant.toString() : null;
    }
}