package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@DynamoDBTable(tableName = "payments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Payment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    
    @DynamoDBAttribute
    private String userId;
    
    @DynamoDBAttribute
    private String merchantId;
    
    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBTypeConvertedEnum
    private PaymentStatus status = PaymentStatus.PENDING;
    
    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBTypeConvertedEnum
    private PaymentMethod paymentMethod = PaymentMethod.CARD;
    
    @DynamoDBAttribute
    @Builder.Default
    private Double amount = 0.0;
    
    @DynamoDBAttribute
    @Builder.Default
    private String currency = "USD";
    
    @DynamoDBAttribute
    private String transactionHash;
    
    @DynamoDBAttribute
    private String externalTransactionId;
    
    @DynamoDBAttribute
    private String idempotencyKey;
    
    @DynamoDBAttribute
    private String description;
    
    @DynamoDBAttribute
    private String createdAt;
    
    @DynamoDBAttribute
    private String updatedAt;
    
    @DynamoDBAttribute
    private String completedAt;
    
    // Helper methods for Instant conversion
    public Instant getCreatedAt() {
        if (createdAt == null) return null;
        try {
            return Instant.parse(createdAt);
        } catch (Exception e) {
            return null;
        }
    }
    
    public void setCreatedAt(Instant instant) {
        this.createdAt = instant != null ? instant.toString() : null;
    }
    
    public Instant getUpdatedAt() {
        if (updatedAt == null) return null;
        try {
            return Instant.parse(updatedAt);
        } catch (Exception e) {
            return null;
        }
    }
    
    public void setUpdatedAt(Instant instant) {
        this.updatedAt = instant != null ? instant.toString() : null;
    }
    
    public Instant getCompletedAt() {
        if (completedAt == null) return null;
        try {
            return Instant.parse(completedAt);
        } catch (Exception e) {
            return null;
        }
    }
    
    public void setCompletedAt(Instant instant) {
        this.completedAt = instant != null ? instant.toString() : null;
    }
}