// ============================================================================
// File: model/Payment.java
// ============================================================================
package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Payments")
public class Payment {
    
    @DynamoDBHashKey(attributeName = "paymentId")
    private String paymentId;
    
    @DynamoDBRangeKey(attributeName = "timestamp")
    private Long timestamp;
    
    @DynamoDBAttribute(attributeName = "userId")
    private String userId;
    
    @DynamoDBAttribute(attributeName = "amount")
    @DynamoDBTypeConverted(converter = EncryptedStringConverter.class)
    private String amount; // Encrypted
    
    @DynamoDBAttribute(attributeName = "currency")
    private String currency; // KES, USD, EUR, etc.
    
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "paymentMethod")
    private PaymentMethod paymentMethod;
    
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "status")
    private PaymentStatus status;
    
    @DynamoDBAttribute(attributeName = "merchantId")
    private String merchantId;
    
    @DynamoDBAttribute(attributeName = "merchantName")
    private String merchantName;
    
    @DynamoDBAttribute(attributeName = "transactionHash")
    private String transactionHash; // SHA-256 hash for integrity
    
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    
    @DynamoDBAttribute(attributeName = "customerEmail")
    @DynamoDBTypeConverted(converter = EncryptedStringConverter.class)
    private String customerEmail; // Encrypted
    
    @DynamoDBAttribute(attributeName = "customerPhone")
    @DynamoDBTypeConverted(converter = EncryptedStringConverter.class)
    private String customerPhone; // Encrypted
    
    @DynamoDBAttribute(attributeName = "ipAddress")
    private String ipAddress;
    
    @DynamoDBAttribute(attributeName = "deviceFingerprint")
    private String deviceFingerprint;
    
    @DynamoDBAttribute(attributeName = "metadata")
    private String metadata; // JSON string for additional data
    
    @DynamoDBAttribute(attributeName = "providerTransactionId")
    private String providerTransactionId; // M-Pesa or Stripe transaction ID
    
    @DynamoDBAttribute(attributeName = "providerResponse")
    private String providerResponse; // Raw response from payment provider
    
    @DynamoDBAttribute(attributeName = "failureReason")
    private String failureReason;
    
    @DynamoDBAttribute(attributeName = "idempotencyKey")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "IdempotencyIndex")
    private String idempotencyKey; // Prevent duplicate payments
    
    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;
    
    @DynamoDBAttribute(attributeName = "updatedAt")
    private String updatedAt;
    
    @DynamoDBAttribute(attributeName = "completedAt")
    private String completedAt;
    
    @DynamoDBVersionAttribute
    private Long version; // Optimistic locking
    
    // Helper method to set timestamps on creation
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.timestamp == null) {
            this.timestamp = Instant.now().toEpochMilli();
        }
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
        this.updatedAt = Instant.now().toString();
    }
    
    // Custom converter for encrypted fields (placeholder - implement in util)
    public static class EncryptedStringConverter implements DynamoDBTypeConverter<String, String> {
        @Override
        public String convert(String value) {
            // Encryption logic will be implemented in EncryptionUtil
            return value; // Placeholder
        }
        
        @Override
        public String unconvert(String value) {
            // Decryption logic will be implemented in EncryptionUtil
            return value; // Placeholder
        }
    }
}
