// ============================================================================
// File: model/PaymentTransaction.java
// ============================================================================
package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "TransactionLogs")
public class PaymentTransaction {

    @DynamoDBHashKey(attributeName = "transactionId")
    private String transactionId;

    @DynamoDBRangeKey(attributeName = "timestamp")
    private Long timestamp;

    @DynamoDBAttribute(attributeName = "paymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PaymentIdIndex")
    private String paymentId;

    @DynamoDBAttribute(attributeName = "eventType")
    private String eventType; // INITIATED, PROCESSING, COMPLETED, FAILED, WEBHOOK_RECEIVED

    @DynamoDBAttribute(attributeName = "payload")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String payload; // Encrypted JSON payload

    @DynamoDBAttribute(attributeName = "signature")
    private String signature; // HMAC-SHA256 signature

    @DynamoDBAttribute(attributeName = "verified")
    private Boolean verified;

    @DynamoDBAttribute(attributeName = "source")
    private String source; // INTERNAL, MPESA, STRIPE, QR_CODE

    @DynamoDBAttribute(attributeName = "ipAddress")
    private String ipAddress;

    @DynamoDBAttribute(attributeName = "userAgent")
    private String userAgent;

    @DynamoDBAttribute(attributeName = "errorMessage")
    private String errorMessage;

    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.timestamp == null) {
            this.timestamp = Instant.now().toEpochMilli();
        }
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
    }
}
