// ============================================================================
// File: model/QRPayment.java
// ============================================================================
package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "QRPayments")
public class QRPayment {
    
    @DynamoDBHashKey(attributeName = "qrCodeToken")
    private String qrCodeToken; // Unique token for QR code
    
    @DynamoDBRangeKey(attributeName = "expiryTimestamp")
    @DynamoDBTypeConvertedTimestamp(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timeZone = "UTC")
    private Long expiryTimestamp; // TTL for auto-deletion
    
    @DynamoDBAttribute(attributeName = "paymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PaymentIdIndex")
    private String paymentId;
    
    @DynamoDBAttribute(attributeName = "merchantId")
    private String merchantId;
    
    @DynamoDBAttribute(attributeName = "merchantName")
    private String merchantName;
    
    @DynamoDBAttribute(attributeName = "amount")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String amount; // Encrypted
    
    @DynamoDBAttribute(attributeName = "currency")
    private String currency;
    
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "status")
    private PaymentStatus status;
    
    @DynamoDBAttribute(attributeName = "qrCodeData")
    private String qrCodeData; // Encrypted QR data
    
    @DynamoDBAttribute(attributeName = "qrCodeImage")
    private String qrCodeImage; // Base64 encoded QR image
    
    @DynamoDBAttribute(attributeName = "totp")
    private String totp; // Time-based one-time password
    
    @DynamoDBAttribute(attributeName = "totpSecret")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String totpSecret; // Encrypted TOTP secret
    
    @DynamoDBAttribute(attributeName = "usedAt")
    private String usedAt;
    
    @DynamoDBAttribute(attributeName = "scannedAt")
    private String scannedAt;
    
    @DynamoDBAttribute(attributeName = "scanCount")
    private Integer scanCount;
    
    @DynamoDBAttribute(attributeName = "ipAddress")
    private String ipAddress;
    
    @DynamoDBAttribute(attributeName = "deviceFingerprint")
    private String deviceFingerprint;
    
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    
    @DynamoDBAttribute(attributeName = "maxScans")
    private Integer maxScans; // Limit number of scans (default: 1)
    
    @DynamoDBAttribute(attributeName = "singleUse")
    private Boolean singleUse; // True = can only be used once
    
    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;
    
    @DynamoDBAttribute(attributeName = "updatedAt")
    private String updatedAt;
    
    @DynamoDBVersionAttribute
    private Long version;
    
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
        this.updatedAt = Instant.now().toString();
    }
    
    public boolean isExpired() {
        return Instant.now().toEpochMilli() > this.expiryTimestamp;
    }
    
    public boolean isUsed() {
        return this.status == PaymentStatus.COMPLETED || this.usedAt != null;
    }
}
