package com.allyticlabs.backend.model;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "QRPayments")
public class QRPayment {
    
    @DynamoDBHashKey(attributeName = "qrCodeToken")
    private String qrCodeToken;
    
    @DynamoDBRangeKey(attributeName = "expiryTimestamp")
    @DynamoDBTypeConvertedTimestamp(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", timeZone = "UTC")
    private Long expiryTimestamp;
    
    @DynamoDBAttribute(attributeName = "qrPaymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "QRPaymentIdIndex")
    private String qrPaymentId;
    
    @DynamoDBAttribute(attributeName = "paymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PaymentIdIndex")
    private String paymentId;
    
    @DynamoDBAttribute(attributeName = "merchantId")
    private String merchantId;
    
    @DynamoDBAttribute(attributeName = "merchantName")
    private String merchantName;
    
    @DynamoDBAttribute(attributeName = "amount")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String amount;
    
    @DynamoDBAttribute(attributeName = "currency")
    private String currency;
    
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "status")
    private PaymentStatus status;
    
    @DynamoDBAttribute(attributeName = "qrCodeData")
    private String qrCodeData;
    
    @DynamoDBAttribute(attributeName = "qrCodeImage")
    private String qrCodeImage;
    
    @DynamoDBAttribute(attributeName = "totp")
    private String totp;
    
    @DynamoDBAttribute(attributeName = "totpSecret")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String totpSecret;
    
    @DynamoDBAttribute(attributeName = "used")
    private Boolean used;
    
    @DynamoDBAttribute(attributeName = "usedAt")
    private String usedAt;
    
    @DynamoDBAttribute(attributeName = "scannedAt")
    private String scannedAt;
    
    @DynamoDBAttribute(attributeName = "scanCount")
    private Integer scanCount;
    
    @DynamoDBAttribute(attributeName = "ipAddress")
    private String ipAddress;
    
    @DynamoDBAttribute(attributeName = "deviceFingerprint")
    private String deviceFingerprint;
    
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    
    @DynamoDBAttribute(attributeName = "maxScans")
    private Integer maxScans;
    
    @DynamoDBAttribute(attributeName = "singleUse")
    private Boolean singleUse;
    
    @DynamoDBAttribute(attributeName = "expiresAt")
    private String expiresAt;
    
    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;
    
    @DynamoDBAttribute(attributeName = "updatedAt")
    private String updatedAt;
    
    @DynamoDBVersionAttribute
    private Long version;
    
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
        this.updatedAt = Instant.now().toString();
        
        if (this.expiresAt == null && this.expiryTimestamp != null) {
            this.expiresAt = Instant.ofEpochMilli(this.expiryTimestamp).toString();
        }
    }
    
    public boolean isExpired() {
        if (expiryTimestamp != null) {
            return Instant.now().toEpochMilli() > this.expiryTimestamp;
        }
        if (expiresAt != null) {
            return Instant.now().isAfter(Instant.parse(expiresAt));
        }
        return false;
    }
    
    public boolean isUsed() {
        return this.status == PaymentStatus.COMPLETED || this.used == Boolean.TRUE || this.usedAt != null;
    }
    
    // Compatibility methods
    public Instant getExpiresAt() {
        if (expiresAt != null) {
            return Instant.parse(expiresAt);
        }
        if (expiryTimestamp != null) {
            return Instant.ofEpochMilli(expiryTimestamp);
        }
        return null;
    }
    
    public void setExpiresAt(Instant instant) {
        if (instant != null) {
            this.expiresAt = instant.toString();
            this.expiryTimestamp = instant.toEpochMilli();
        }
    }
    
    public void setUsed(boolean used) {
        this.used = used;
        if (used && this.usedAt == null) {
            this.usedAt = Instant.now().toString();
        }
    }
}
