// ============================================================================
// File: model/StripePayment.java
// ============================================================================
package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "StripePayments")
public class StripePayment {

    @DynamoDBHashKey(attributeName = "stripePaymentIntentId")
    private String stripePaymentIntentId;

    @DynamoDBRangeKey(attributeName = "timestamp")
    private Long timestamp;

    @DynamoDBAttribute(attributeName = "paymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PaymentIdIndex")
    private String paymentId;

    @DynamoDBAttribute(attributeName = "stripeCustomerId")
    private String stripeCustomerId;

    @DynamoDBAttribute(attributeName = "amount")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String amount; // Encrypted, in cents

    @DynamoDBAttribute(attributeName = "currency")
    private String currency;

    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    @DynamoDBAttribute(attributeName = "status")
    private PaymentStatus status;

    @DynamoDBAttribute(attributeName = "stripeStatus")
    private String stripeStatus; // requires_payment_method, requires_confirmation, succeeded, etc.

    @DynamoDBAttribute(attributeName = "paymentMethodId")
    private String paymentMethodId;

    @DynamoDBAttribute(attributeName = "paymentMethodType")
    private String paymentMethodType; // card, bank_transfer, etc.

    @DynamoDBAttribute(attributeName = "cardLast4")
    private String cardLast4;

    @DynamoDBAttribute(attributeName = "cardBrand")
    private String cardBrand; // visa, mastercard, amex

    @DynamoDBAttribute(attributeName = "clientSecret")
    @DynamoDBTypeConverted(converter = Payment.EncryptedStringConverter.class)
    private String clientSecret; // Encrypted

    @DynamoDBAttribute(attributeName = "receiptUrl")
    private String receiptUrl;

    @DynamoDBAttribute(attributeName = "chargeId")
    private String chargeId;

    @DynamoDBAttribute(attributeName = "balanceTransactionId")
    private String balanceTransactionId;

    @DynamoDBAttribute(attributeName = "refundId")
    private String refundId;

    @DynamoDBAttribute(attributeName = "stripeResponse")
    private String stripeResponse; // Raw Stripe API response

    @DynamoDBAttribute(attributeName = "failureCode")
    private String failureCode;

    @DynamoDBAttribute(attributeName = "failureMessage")
    private String failureMessage;

    @DynamoDBAttribute(attributeName = "threeDSecureStatus")
    private String threeDSecureStatus; // 3D Secure authentication status

    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;

    @DynamoDBAttribute(attributeName = "updatedAt")
    private String updatedAt;

    @DynamoDBVersionAttribute
    private Long version;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.timestamp == null) {
            this.timestamp = Instant.now().toEpochMilli();
        }
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
        this.updatedAt = Instant.now().toString();
    }
}
