
// ============================================================================
// File: model/Webhook.java
// ============================================================================
package com.allyticlabs.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "WebhookLogs")
public class Webhook {
    
    @DynamoDBHashKey(attributeName = "webhookId")
    private String webhookId;
    
    @DynamoDBRangeKey(attributeName = "timestamp")
    private Long timestamp;
    
    @DynamoDBAttribute(attributeName = "paymentId")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PaymentIdIndex")
    private String paymentId;
    
    @DynamoDBAttribute(attributeName = "provider")
    private String provider; // MPESA, STRIPE
    
    @DynamoDBAttribute(attributeName = "eventType")
    private String eventType;
    
    @DynamoDBAttribute(attributeName = "payload")
    private String payload; // Raw webhook payload
    
    @DynamoDBAttribute(attributeName = "signature")
    private String signature; // Webhook signature
    
    @DynamoDBAttribute(attributeName = "verified")
    private Boolean verified;
    
    @DynamoDBAttribute(attributeName = "processed")
    private Boolean processed;
    
    @DynamoDBAttribute(attributeName = "processingStatus")
    private String processingStatus; // SUCCESS, FAILED, PENDING
    
    @DynamoDBAttribute(attributeName = "errorMessage")
    private String errorMessage;
    
    @DynamoDBAttribute(attributeName = "retryCount")
    private Integer retryCount;
    
    @DynamoDBAttribute(attributeName = "ipAddress")
    private String ipAddress;
    
    @DynamoDBAttribute(attributeName = "userAgent")
    private String userAgent;
    
    @DynamoDBAttribute(attributeName = "headers")
    private String headers; // JSON string of request headers
    
    @DynamoDBAttribute(attributeName = "createdAt")
    private String createdAt;
    
    @DynamoDBAttribute(attributeName = "processedAt")
    private String processedAt;
    
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public void onPreSave() {
        if (this.timestamp == null) {
            this.timestamp = Instant.now().toEpochMilli();
        }
        if (this.createdAt == null) {
            this.createdAt = Instant.now().toString();
        }
    }
}