package com.bellatechnologies.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@DynamoDBTable(tableName = "payment_transactions")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentTransaction {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String paymentId;

    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBTypeConvertedEnum
    private PaymentStatus status = PaymentStatus.PENDING;

    @DynamoDBAttribute
    @Builder.Default
    @DynamoDBTypeConvertedEnum
    private PaymentMethod method = PaymentMethod.CARD;

    @DynamoDBAttribute
    @Builder.Default
    private Double amount = 0.0;

    @DynamoDBAttribute
    @Builder.Default
    private String transactionId = "";

    @DynamoDBAttribute
    private String transactionType; // Added to replace 'event'

    @DynamoDBAttribute
    private String errorMessage; // Added for error tracking

    @DynamoDBAttribute
    private String metadata; // Additional metadata as JSON string

    @DynamoDBAttribute
    private String createdAt;

    @DynamoDBAttribute
    private String updatedAt;

    // Helper methods for Instant conversion
    public Instant getCreatedAtInstant() {
        if (createdAt == null) return null;
        try {
            return Instant.parse(createdAt);
        } catch (Exception e) {
            return null;
        }
    }

    public void setCreatedAt(Instant instant) {
        this.createdAt = instant != null ? instant.toString() : null;
    }

    public Instant getUpdatedAtInstant() {
        if (updatedAt == null) return null;
        try {
            return Instant.parse(updatedAt);
        } catch (Exception e) {
            return null;
        }
    }

    public void setUpdatedAt(Instant instant) {
        this.updatedAt = instant != null ? instant.toString() : null;
    }
}
