package com.bellatechnologies.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;

@DynamoDBTable(tableName = "stripe_payments")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StripePayment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String paymentIntentId;

    @DynamoDBAttribute
    private String stripePaymentIntentId;

    @DynamoDBAttribute
    private Double amount;

    @DynamoDBAttribute
    private String currency;

    @DynamoDBAttribute
    private String customerId;

    @DynamoDBAttribute
    private String status; // String to store PaymentStatus enum name

    @DynamoDBAttribute
    private String stripeStatus;

    @DynamoDBAttribute
    private String paymentId;

    @DynamoDBAttribute
    private String refundId;

    @DynamoDBAttribute
    private String refundAmount; // String to store Double

    @DynamoDBAttribute
    private String createdAt;

    @DynamoDBAttribute
    private String updatedAt;

    // Helper methods for PaymentStatus conversion
    public PaymentStatus getStatusEnum() {
        if (status == null) return PaymentStatus.PENDING;
        try {
            return PaymentStatus.valueOf(status);
        } catch (Exception e) {
            return PaymentStatus.PENDING;
        }
    }

    public void setStatus(PaymentStatus paymentStatus) {
        this.status = paymentStatus != null ? paymentStatus.name() : PaymentStatus.PENDING.name();
    }

    // Helper methods for refund amount conversion
    public Double getRefundAmountDouble() {
        if (refundAmount == null) return null;
        try {
            return Double.parseDouble(refundAmount);
        } catch (Exception e) {
            return null;
        }
    }

    public void setRefundAmount(Double amount) {
        this.refundAmount = amount != null ? String.valueOf(amount) : null;
    }

    // Helper methods for Instant conversion
    public Instant getCreatedAtInstant() {
        if (createdAt == null) return null;
        try {
            return Instant.parse(createdAt);
        } catch (Exception e) {
            return null;
        }
    }

    public void setCreatedAt(Instant instant) {
        this.createdAt = instant != null ? instant.toString() : null;
    }

    public Instant getUpdatedAtInstant() {
        if (updatedAt == null) return null;
        try {
            return Instant.parse(updatedAt);
        } catch (Exception e) {
            return null;
        }
    }

    public void setUpdatedAt(Instant instant) {
        this.updatedAt = instant != null ? instant.toString() : null;
    }
}
